### PR TITLE
Misc new snippets

### PR DESCRIPTION
**Pull request by tadeoos**
Hey!

This PR is adding three snippets that I use a lot.
I figured there is no reason for them to lay only locally in my `.cson` ;)

### CODE REVIEW

**Comment by tadeoos** [comment]
@draperjames what are your thoghts?

**Comment by draperjames** [comment]
These look great thank-you! Congrats you have the first PR.

**Comment by tadeoos** [comment]
Thanks for the merge, how do you think about a new release with the merged PRs?

**Comment by draperjames** [comment]
Yeah no prob.

**Pull request merged**
